version: '3'
services:
  worker:
    image: jupyter/scipy-notebook
    restart: always
    ports:
      - 12000:8888
    volumes:
      - ${WORK_HOME:-./data}:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
